//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudiHelper.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modul
    {
        public Modul()
        {
            this.Curs = new HashSet<Curs>();
        }
    
        public int moduleID { get; set; }
        public int number { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<Curs> Curs { get; set; }
    }
}
