//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudiHelper.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tutor
    {
        public Tutor()
        {
            this.Lessons = new HashSet<Lesson>();
        }
    
        public int tutorID { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Lesson> Lessons { get; set; }
    }
}
